//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vet_Clinic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vet_Clinic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1111 {
            get {
                object obj = ResourceManager.GetObject("1111", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _120px_Red_X_svg {
            get {
                object obj = ResourceManager.GetObject("120px-Red_X.svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2 {
            get {
                object obj = ResourceManager.GetObject("2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _21 {
            get {
                object obj = ResourceManager.GetObject("21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2121 {
            get {
                object obj = ResourceManager.GetObject("2121", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _21211 {
            get {
                object obj = ResourceManager.GetObject("21211", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2הוסף_לסל {
            get {
                object obj = ResourceManager.GetObject("2הוסף לסל", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2הוספת_בדיקות {
            get {
                object obj = ResourceManager.GetObject("2הוספת בדיקות", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2הוספת_מוצר {
            get {
                object obj = ResourceManager.GetObject("2הוספת מוצר", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2הוספת_רנטגן {
            get {
                object obj = ResourceManager.GetObject("2הוספת רנטגן", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2לוגו {
            get {
                object obj = ResourceManager.GetObject("2לוגו", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2עריכת_מוצר {
            get {
                object obj = ResourceManager.GetObject("2עריכת מוצר", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _3 {
            get {
                object obj = ResourceManager.GetObject("3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _3הוספת_בדיקות {
            get {
                object obj = ResourceManager.GetObject("3הוספת בדיקות", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _4 {
            get {
                object obj = ResourceManager.GetObject("4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _41 {
            get {
                object obj = ResourceManager.GetObject("41", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pows {
            get {
                object obj = ResourceManager.GetObject("pows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wallpaper {
            get {
                object obj = ResourceManager.GetObject("wallpaper", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap warning_icon {
            get {
                object obj = ResourceManager.GetObject("warning-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap איך_סימן_שאלה_01 {
            get {
                object obj = ResourceManager.GetObject("איך סימן שאלה-01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap בטל_SMS {
            get {
                object obj = ResourceManager.GetObject("בטל SMS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap בטל_בחירה_01 {
            get {
                object obj = ResourceManager.GetObject("בטל בחירה-01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap בטל_בחירה_בינוני {
            get {
                object obj = ResourceManager.GetObject("בטל בחירה בינוני", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap בטל_כתום {
            get {
                object obj = ResourceManager.GetObject("בטל כתום", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap דוח_ללקוח {
            get {
                object obj = ResourceManager.GetObject("דוח ללקוח", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap דף_אודות {
            get {
                object obj = ResourceManager.GetObject("דף אודות", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap דף_אודות2 {
            get {
                object obj = ResourceManager.GetObject("דף אודות2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap הוסף_לסל {
            get {
                object obj = ResourceManager.GetObject("הוסף לסל", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap הוספת_בדיקות {
            get {
                object obj = ResourceManager.GetObject("הוספת בדיקות", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap הוספת_חיה {
            get {
                object obj = ResourceManager.GetObject("הוספת חיה", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap הוספת_מוצר {
            get {
                object obj = ResourceManager.GetObject("הוספת מוצר", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap הוספת_רנטגן {
            get {
                object obj = ResourceManager.GetObject("הוספת רנטגן", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap הזנת_חיסונים {
            get {
                object obj = ResourceManager.GetObject("הזנת חיסונים", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap הזנת_חיסונים_האמיתי {
            get {
                object obj = ResourceManager.GetObject("הזנת חיסונים האמיתי", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap היסטוריה {
            get {
                object obj = ResourceManager.GetObject("היסטוריה", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap היסטוריה1 {
            get {
                object obj = ResourceManager.GetObject("היסטוריה1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap הסרה {
            get {
                object obj = ResourceManager.GetObject("הסרה", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap הסרת_התראה_01 {
            get {
                object obj = ResourceManager.GetObject("הסרת התראה-01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap חבילת_בריאות {
            get {
                object obj = ResourceManager.GetObject("חבילת בריאות", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap חבילת_בריאות2 {
            get {
                object obj = ResourceManager.GetObject("חבילת בריאות2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap חיה_חדשה_01 {
            get {
                object obj = ResourceManager.GetObject("חיה חדשה-01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap חיסונים_חדשים {
            get {
                object obj = ResourceManager.GetObject("חיסונים חדשים", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap לוגו {
            get {
                object obj = ResourceManager.GetObject("לוגו", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap לקוח_חדש_01 {
            get {
                object obj = ResourceManager.GetObject("לקוח חדש-01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap מחיקת_מוצר {
            get {
                object obj = ResourceManager.GetObject("מחיקת מוצר", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap נקה_01 {
            get {
                object obj = ResourceManager.GetObject("נקה-01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap נקה_ארוך {
            get {
                object obj = ResourceManager.GetObject("נקה ארוך", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap סל_קניות_01 {
            get {
                object obj = ResourceManager.GetObject("סל קניות-01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap סל_קניות_ארוך {
            get {
                object obj = ResourceManager.GetObject("סל קניות ארוך", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap סל_קניות_בינוני {
            get {
                object obj = ResourceManager.GetObject("סל קניות בינוני", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap עריכת_טיפול {
            get {
                object obj = ResourceManager.GetObject("עריכת טיפול", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap עריכת_מוצר {
            get {
                object obj = ResourceManager.GetObject("עריכת מוצר", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap עריכתפרטים {
            get {
                object obj = ResourceManager.GetObject("עריכתפרטים", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap צפיה_בבדיקות {
            get {
                object obj = ResourceManager.GetObject("צפיה בבדיקות", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap צפיה_ברנטגן {
            get {
                object obj = ResourceManager.GetObject("צפיה ברנטגן", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap רישיון_כלבת_ריק {
            get {
                object obj = ResourceManager.GetObject("רישיון כלבת ריק", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap רקע_מפוספס_בהיר {
            get {
                object obj = ResourceManager.GetObject("רקע מפוספס בהיר", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap רקע_רגל {
            get {
                object obj = ResourceManager.GetObject("רקע רגל", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap רקע_רגל_בהיר {
            get {
                object obj = ResourceManager.GetObject("רקע רגל בהיר", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap שולם {
            get {
                object obj = ResourceManager.GetObject("שולם", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap שליחת_SMS {
            get {
                object obj = ResourceManager.GetObject("שליחת SMS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap שמירה_01_01 {
            get {
                object obj = ResourceManager.GetObject("שמירה-01-01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap שמירה_ארוך {
            get {
                object obj = ResourceManager.GetObject("שמירה ארוך", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap שמירה_סגול {
            get {
                object obj = ResourceManager.GetObject("שמירה סגול", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
